<section id="subfooter">
    <h2>Онлайн кинотеатр Cosmovie</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at blanditiis deleniti ea fuga, incidunt molestias nihil nulla placeat reiciendis repellendus rerum soluta veniam voluptatibus voluptatum. Blanditiis culpa dolor doloribus ducimus itaque labore, laborum libero molestias mollitia numquam, possimus quaerat rem sint veniam voluptatem. Aperiam atque commodi cum eveniet explicabo fuga harum laboriosam laudantium libero molestias, nam nisi praesentium provident quia quod rem suscipit! Animi aut consectetur hic iusto quaerat quos repellendus sed voluptatibus? At blanditiis corporis delectus deserunt dolore eaque hic ipsa iure laboriosam libero, placeat quas ullam. Assumenda harum non possimus quas, quibusdam sunt tempora? Animi autem consequuntur cum debitis dignissimos illo magnam modi, nesciunt odio officia provident quidem ratione sint, voluptatem, voluptatum! Adipisci autem consequuntur debitis dolor eaque esse est facere fuga hic inventore ipsum itaque iure iusto natus nemo nostrum nulla numquam, obcaecati quo reiciendis repellat, totam ut veritatis vero, voluptatem. Consequatur ipsam iste mollitia nam repudiandae. Adipisci alias, consequatur impedit quidem quisquam sequi voluptas? Aliquid at atque cupiditate doloribus hic itaque labore obcaecati officiis pariatur. Ad architecto assumenda, at blanditiis, dicta dolores fugit ipsa ipsum itaque, labore modi mollitia nam perferendis quaerat quidem quisquam reiciendis repellat repudiandae similique soluta suscipit vero voluptatem? Dignissimos enim, quidem?
    </p>
    <h3>
        Лучшие фильмы и сериалы
    </h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur aut consequuntur dolor ducimus eligendi error ex laborum nemo nihil nulla numquam perspiciatis ratione reiciendis repellendus saepe sequi, soluta totam ullam veniam, voluptatem. Amet architecto aspernatur assumenda autem dignissimos distinctio, dolorum eum eveniet exercitationem fugiat harum incidunt inventore minima modi perferendis quam, quibusdam quidem, quo quos sit vitae voluptatem voluptatibus. Accusantium ad aliquam, deserunt distinctio doloribus earum eius eligendi eveniet exercitationem facere harum illo illum ipsa, ipsam laboriosam laudantium libero maiores minima molestias necessitatibus nemo nesciunt nobis officiis optio pariatur praesentium qui recusandae repellat rerum similique tempore vel velit voluptate. Beatae cupiditate distinctio error facere neque nihil quos recusandae sapiente sit voluptate! Commodi incidunt necessitatibus odit officiis praesentium quas rerum, vitae voluptas? Aliquid aperiam asperiores autem debitis dignissimos, eligendi, enim eos facilis incidunt, iusto laudantium minus molestiae nam nostrum odio quibusdam quisquam quo velit vitae voluptates! Ab distinctio eaque modi quibusdam!
    </p>
</section>